sched: Remove duplicate definition of mmget_still_valid
I should have compiled my merge but it was during an ALS release so I
was not as diligent as I should have been.

In file included from ../arch/arm64/kernel/asm-offsets.c:22:0:
../include/linux/mm.h:1244:20: error: redefinition of 'mmget_still_valid'
 static inline bool mmget_still_valid(struct mm_struct *mm)
                    ^
In file included from ../arch/arm64/kernel/asm-offsets.c:21:0:
../include/linux/sched.h:3305:20: note: previous definition of 'mmget_still_valid' was here
 static inline bool mmget_still_valid(struct mm_struct *mm)
                    ^

Fixes: 2fed8ed3867c ("Merge remote-tracking branch 'upstream/oneplus/SDM845_Q_10.0' into oneplus/SDM845_Q_10.0")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>